a = 0
while a < 10: 
	a = a + 1
	popup("")
	#PAGE1
	type("0IamthebusiestpenguinIknow")
	type("CleaningthewindowsattheDojo")
	type("Wipingthemdownandgettingthemshined")
	type("Makingsurenoonehasleftstreaksbehind")
	popup("")
	#PAGE2
	type("ThenonedaywhileIwasworkingaway")
	type("Wouldntyouknowitsomepenguinstheycame")
	type("andbroughtthiscontainerasbigasatree")
	type("andfilledtothetopwithglowinglimegreen")
	popup("")
	#PAGE3
	type("Igazedinamazementastheyfellin")
	type("Thenoneofthemspoketomewithagrin")
	type("Itsacolorfulpartyforalltoexpress")
	type("Butwhilehewassohappytheplacewasamess")
	popup("")
	#PAGE4
	type("Therewaspaintonthewallsandpaintontheceiling")
	type("Thispaintsplatteredplacewassounappealing")
	type("AndjustwhenIthoughtIcouldtakeitnomore")
	type("apenguinbegantomaketracksonthefloor")
	popup("")
	#PAGE5
	type("IjustcleanedthefloorIloudlyproclaimed")
	type("AndnowIwillhavetogomopitagain")
	type("ButwouldntyouknowitthismopthatIused")
	type("Wasdroppedinthebucketoflimecoloredooze")
	popup("")
	#PAGE6
	type("NowIfacedadecisionofjustwhattodo")
	type("Mymopwasunusablethankstothiscrew")
	type("TheragsthatIusedwerejustfartoowornout")
	type("SoIstoodonthatpaintcanandstartedtoshout")
	popup("")
	#PAGE7
	type("ThenapenguinrespondedYouseemsoupset")
	type("Itstimeforapartybutdidyouforget")
	type("Perhapstheresawayformetohelpyou")
	type("AndIthinkthatIknowjustwhatweshoulddo")
	popup("")
	#PAGE8
	type("Thepenguinshepointedtowardsalargebox")
	type("Containingsomecapesandacoupleoldsocks")
	type("Letsuseupthesecapestocleanupthemess")
	type("NowthatsanideaIwouldnthaveguessed")
	popup("")
	#PAGE9
	type("Whenthepartywasovertheneveryonejoined")
	type("TheyhelpedcleantheDojowithoutneedingacoin")
	type("Andwhenweweredonetheplacewassoperfect")
	type("Youdneverhaveguesseditwasonceagreenwreck")
	type("TheEnd")