#NoEnv
SendMode Input

Submit(x)
{
	Send ^a{Del} 
	Send %x%
}

Esc::ExitApp

Shift::
Submit("Afghanistan")
Submit("Albania")
Submit("Algeria")
Submit("Andorra")
Submit("Angola")
Submit("Antigua and Barbuda")
Submit("Argentina")
Submit("Armenia")
Submit("Australia")
Submit("Austria")
Submit("Azerbaijan")
Submit("Bahamas")
Submit("Bahrain")
Submit("Bangladesh")
Submit("Barbados")
Submit("Belarus")
Submit("Belgium")
Submit("Belize")
Submit("Benin")
Submit("Bhutan")
Submit("Bolivia")
Submit("Bosnia and Herzegovina")
Submit("Botswana")
Submit("Brazil")
Submit("Brunei")
Submit("Bulgaria")
Submit("Burkina Faso")
Submit("Burundi")
Submit("Cabo Verde")
Submit("Cambodia")
Submit("Cameroon")
Submit("Canada")
Submit("Central African Republic")
Submit("Chad")
Submit("Chile")
Submit("China")
Submit("Colombia")
Submit("Comoros")
Submit("Democratic Republic of the Congo")
Submit("Republic of the Congo")
Submit("Costa Rica")
Submit("Ivory Coast")
Submit("Croatia")
Submit("Cuba")
Submit("Cyprus")
Submit("Czech Republic")
Submit("Denmark")
Submit("Djibouti")
Submit("Dominica")
Submit("Dominican Republic")
Submit("Ecuador")
Submit("Egypt")
Submit("El Salvador")
Submit("Equatorial Guinea")
Submit("Eritrea")
Submit("Estonia")
Submit("Ethiopia")
Submit("Fiji")
Submit("Finland")
Submit("France")
Submit("Gabon")
Submit("Gambia")
Submit("Georgia")
Submit("Germany")
Submit("Ghana")
Submit("Greece")
Submit("Grenada")
Submit("Guatemala")
Submit("Guinea")
Submit("Guinea-Bissau")
Submit("Guyana")
Submit("Haiti")
Submit("Honduras")
Submit("Hungary")
Submit("Iceland")
Submit("India")
Submit("Indonesia")
Submit("Iran")
Submit("Iraq")
Submit("Ireland")
Submit("Israel")
Submit("Italy")
Submit("Jamaica")
Submit("Japan")
Submit("Jordan")
Submit("Kazakhstan")
Submit("Kenya")
Submit("Kiribati")
Submit("Kosovo")
Submit("Kuwait")
Submit("Kyrgyzstan")
Submit("Laos")
Submit("Latvia")
Submit("Lebanon")
Submit("Lesotho")
Submit("Liberia")
Submit("Libya")
Submit("Liechtenstein")
Submit("Lithuania")
Submit("Luxembourg")
Submit("Macedonia")
Submit("Madagascar")
Submit("Malawi")
Submit("Malaysia")
Submit("Maldives")
Submit("Mali")
Submit("Malta")
Submit("Marshall Islands")
Submit("Mauritania")
Submit("Mauritius")
Submit("Mexico")
Submit("Micronesia")
Submit("Moldova")
Submit("Monaco")
Submit("Mongolia")
Submit("Montenegro")
Submit("Morocco")
Submit("Mozambique")
Submit("Myanmar")
Submit("Namibia")
Submit("Nauru")
Submit("Nepal")
Submit("Netherlands")
Submit("New Zealand")
Submit("Nicaragua")
Submit("Niger")
Submit("Nigeria")
Submit("North Korea")
Submit("Norway")
Submit("Oman")
Submit("Pakistan")
Submit("Palau")
Submit("Palestine")
Submit("Panama")
Submit("Papua New Guinea")
Submit("Paraguay")
Submit("Peru")
Submit("Philippines")
Submit("Poland")
Submit("Portugal")
Submit("Qatar")
Submit("Romania")
Submit("Russia")
Submit("Rwanda")
Submit("Saint Kitts and Nevis")
Submit("Saint Lucia")
Submit("Saint Vincent")
Submit("Samoa")
Submit("San Marino")
Submit("Sao Tome and Principe")
Submit("Saudi Arabia")
Submit("Senegal")
Submit("Serbia")
Submit("Seychelles")
Submit("Sierra Leone")
Submit("Singapore")
Submit("Slovakia")
Submit("Slovenia")
Submit("Solomon Islands")
Submit("Somalia")
Submit("South Africa")
Submit("South Korea")
Submit("South Sudan")
Submit("Spain")
Submit("Sri Lanka")
Submit("Sudan")
Submit("Suriname")
Submit("Swaziland")
Submit("Sweden")
Submit("Switzerland")
Submit("Syria")
Submit("Taiwan")
Submit("Tajikistan")
Submit("Tanzania")
Submit("Thailand")
Submit("Timor-Leste")
Submit("Togo")
Submit("Tonga")
Submit("Trinidad and Tobago")
Submit("Tunisia")
Submit("Turkey")
Submit("Turkmenistan")
Submit("Tuvalu")
Submit("Uganda")
Submit("United Kingdom")
Submit("Ukraine")
Submit("United Arab Emirates")
Submit("United States")
Submit("Uruguay")
Submit("Uzbekistan")
Submit("Vanuatu")
Submit("Vatican")
Submit("Venezuela")
Submit("Vietnam")
Submit("Yemen")
Submit("Zambia")
Submit("Zimbabwe")
